### REGISTER USER
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "email": "timi1@gmail.com",
    "password":"12345678",
    "firstName":"John",
    "lastName":"Doe",
    "phone":"08012345678"
}


### LOGIN USER
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "timi@gmail.com",
    "password":"12345678"
}

### VERIFY EMAIL
GET http://localhost:5000/api/users/verify-email?emailVerificationCode=timirt1@gmail.com940940
Content-Type: application/json


### RESEND VERIFY EMAIL
POST http://localhost:5000/api/users/resend-verification-email
Content-Type: application/json

{
    "email": "timirt11@gmail.com"
}

### CHANGE PASSWORD
PUT http://localhost:5000/api/users/change-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0aW1pQGdtYWlsLmNvbSIsImlhdCI6MTY4NjI5ODg2NCwiZXhwIjoxNjg2MzAwMzA0fQ.nLJtNh76E_F7NpTK1A2K0xO0Npxtlx9lLriftAiC0_U

{
    "oldPassword": "12345678",
    "newPassword": "12345678"
}
