server:
  port: 5000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${env.DATABASE_USERNAME}
    url: ${env.DATABASE_URL}
    password: ${env.DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'